# Generated by Django 5.1.1 on 2024-09-24 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 2, 23, 27, 760396, tzinfo=datetime.timezone.utc)),
        ),
    ]
